---
title: TrueCoders
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  team:
    title: Team Members
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: page
    permalink: "/blog/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
    display_title: 
- scope:
    path: ''
    type: team
  values:
    layout: page
    company_title: 
    profile_image: 
    is_teacher: false
url: http://truecoders.io
email: contact@truecoders.io
description: Crafted Culture and Talent
author:
  picture: "/uploads/cody-winton.jpg"
  twitter: codytwinton
google_analytics:
  tracking_id: UA-104643272-1
logo: "/uploads/logo.png"
plugins:
- jekyll-feed
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
sass:
  sass_dir: styles/
  style: compressed
social:
  name: TrueCoders
  links:
  - https://twitter.com/truecodersio
  - https://www.facebook.com/truecodersio
  - https://www.linkedin.com/in/truecodersio
  - https://github.com/truecodersio
twitter:
  username: truecodersio
baseurl: 
markdown: kramdown
permalink: pretty
