---
title: TrueCoders
timezone: America/Chicago
collections:
  courses:
    title: Courses
    output: true
  posts:
    title: Posts
    output: true
  team:
    title: Team Members
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: courses
  values:
    layout: page
    start_date: 
    end_date: 
    has_scholarship: true
    price: 
- scope:
    path: ''
    type: pages
  values:
    layout: page
    display_title: 
- scope:
    path: index.markdown
    type: pages
  values:
    layout: home
- scope:
    path: faqs.markdown
    type: pages
  values:
    layout: page
    qas:
    - question: 
      answer: 
- scope:
    path: ''
    type: posts
  values:
    layout: page
    permalink: "/blog/:title/"
- scope:
    path: ''
    type: team
  values:
    layout: page
    company_title: 
    is_board_member: false
    is_teacher: false
    profile_image: 
url: http://truecoders.io
email: contact@truecoders.io
description: |-
  Be Mentored. Be Connected.

  We believe that smart, passionate people should always be engaged, doing what they love to do. Our mission is to educate smart and passionate people as they become skilled developers, to keep them engaged working with companies solving real-world problems, and to continue mentoring them as they grow their skill set.
company:
  name: TrueCoders
  full_name: TrueCoders LLC
  primary_color: "#0093C9"
author:
  picture: "/uploads/cody-winton.jpg"
  twitter: codytwinton
google_analytics:
  tracking_id: UA-104643272-1
logo: "/uploads/logo.png"
plugins:
- jekyll-feed
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
sass:
  style: compressed
social:
  name: TrueCoders
  links:
  - https://twitter.com/truecodersio
  - https://www.facebook.com/truecodersio
  - https://www.linkedin.com/in/truecodersio
  - https://github.com/truecodersio
twitter:
  username: truecodersio
assets:
  digest: true
baseurl: 
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
markdown: kramdown
permalink: pretty
