---
title: TrueCoders
timezone: America/Chicago
collections:
  classes:
    title: Classes
    output: false
  coders:
    title: Coders
    output: true
    referencesLimit: 1
  courses:
    title: Courses
    output: true
  faqs:
    title: FAQs
    output: false
  mbtis:
    title: MBTIs
    output: false
  pageSections:
    title: PageSections
    output: false
  posts:
    title: Posts
    output: true
  subjects:
    title: Subjects
    output: false
  teammates:
    title: Teammates
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: classes
  values:
    course: 
    start_date: 
    end_date: 
    price: 
    hasScholarship: true
    location: Birmingham, AL
    institution: TrueCoders
    company: TrueCoders
    jobTitle: Developer
    callToAction:
      title: 
      url: 
- scope:
    path: ''
    type: coders
  values:
    layout: resume
    image: 
    email: 
    phone: 
    website: 
    location:
      address: 
      postalCode: 
      city: 
      countryCode: US
      region: 
    class: 
    profiles:
      mbti: 
      github: 
      linkedin: 
      codewars: 
      video: 
    work:
    - company: 
      jobTitle: 
      start_date: 
      end_date: 
      location: 
      body: 
    education:
    - institution: 
      area: 
      start_date: 
      end_date: 
      gpa: 
      location: 
      body: 
    skills:
    - name: 
      level: 0
    references:
    - name: 
      reference: 
- scope:
    path: ''
    type: courses
  values:
    layout: course
    hero:
      color: "#4b4948"
      image: 
    subtitle: 
    image: 
    start_date: 
    weeksLength: 0
    hasScholarship: true
    price: "$10,000"
    subjects:
    - 
    callToAction:
      title: 
      url: 
- scope:
    path: ''
    type: faqs
  values:
    displayTitle: 
- scope:
    path: ''
    type: pageSections
  values:
    displayTitle: 
    subCollection: 
    limit: 3
    callToAction:
      title: 
      url: 
    subsections:
    - title: 
      subtitle: 
      faIcon: 
      body: 
- scope:
    path: ''
    type: posts
  values:
    layout: page
    permalink: "/blog/:title/"
- scope:
    path: ''
    type: teammates
  values:
    layout: page
    subtitle: 
    isBoardMember: false
    isTeacher: false
    image: 
- scope:
    path: ''
    type: pages
  values:
    layout: page
    isNav: false
    isFooter: false
    hero:
      color: "#4b4948"
      image: 
    displayTitle: 
    subtitle: 
    callToAction:
      title: 
      url: 
- scope:
    path: about.markdown
    type: pages
  values:
    layout: collection-page
    collection: teammates
- scope:
    path: courses.markdown
    type: pages
  values:
    layout: collection-page
    collection: courses
- scope:
    path: coders.markdown
    type: pages
  values:
    layout: collection-page
    collection: coders
- scope:
    path: contact.markdown
    type: pages
  values:
    layout: contact
- scope:
    path: faqs.markdown
    type: pages
  values:
    layout: faqs
- scope:
    path: hire.markdown
    type: pages
  values:
    layout: hire
    pageSections:
    - 
- scope:
    path: index.markdown
    type: pages
  values:
    layout: index
    pageSections:
    - 
url: http://truecoders.io
logo: "/uploads/logo.png"
image: "/uploads/logo.png"
author:
  name: TrueCoders
  twitter: truecodersio
company:
  email: contact@truecoders.io
  fullName: TrueCoders LLC
  phone: 12055308496
  location:
    address: '205 20th Street N #1015'
    city: Birmingham
    postalCode: 35203
    countryCode: US
    region: AL
description: |-
  Be Mentored. Be Connected.

  We believe that smart, passionate people should always be engaged, doing what they love to do. Our mission is to educate smart and passionate people as they become skilled developers, to keep them engaged working with companies solving real-world problems, and to continue mentoring them as they grow their skill set.
googleAnalytics:
  trackingId: UA-104643272-1
social:
  name: TrueCoders
  links:
  - https://twitter.com/truecodersio
  - https://www.facebook.com/truecodersio
  - https://www.linkedin.com/in/truecodersio
  - https://github.com/truecodersio
twitter:
  username: truecodersio
sass:
  style: compressed
baseurl: 
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
markdown: kramdown
permalink: pretty
plugins:
- jekyll-feed
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
