---
title: TrueCoders
timezone: America/Chicago
collections:
  courses:
    title: Courses
    output: true
  posts:
    title: Posts
    output: true
  subjects:
    title: Subjects
    output: false
  team_members:
    title: Team Members
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    is_nav_page: false
    is_footer_page: false
    hero_color: "#4b4948"
    hero_image: 
    display_title: 
    subtitle: 
    call_to_action:
      title: 
      url: 
- scope:
    path: about.markdown
    type: pages
  values:
    layout: about
- scope:
    path: contact.markdown
    type: pages
  values:
    layout: contact
- scope:
    path: faqs.markdown
    type: pages
  values:
    layout: faqs
    qa_items:
    - question: 
      answer: 
- scope:
    path: index.markdown
    type: pages
  values:
    layout: index
    sections:
    - title: 
      collection: 
      limit: 3
      body: 
- scope:
    path: ''
    type: courses
  values:
    layout: course
    hero_color: "#4b4948"
    hero_image: 
    subtitle: 
    image: 
    start_date: 
    weeks_length: 0
    has_scholarship: true
    price: 
    subjects: 
    - 
    call_to_action:
      title: 
      url: 
- scope:
    path: ''
    type: posts
  values:
    layout: page
    permalink: "/blog/:title/"
- scope:
    path: ''
    type: team_members
  values:
    layout: page
    company_title: 
    is_board_member: false
    is_teacher: false
    image: 
url: http://truecoders.io
logo: "/uploads/logo.png"
contact:
  email: contact@truecoders.io
  full_name: TrueCoders LLC
  phone: 12055308496
  address:
    street: 205 20th Street N
    unit: "#1015"
    city: Birmingham
    state: AL
    zip: '35203'
description: |-
  Be Mentored. Be Connected.

  We believe that smart, passionate people should always be engaged, doing what they love to do. Our mission is to educate smart and passionate people as they become skilled developers, to keep them engaged working with companies solving real-world problems, and to continue mentoring them as they grow their skill set.
google_analytics:
  tracking_id: UA-104643272-1
social:
  name: TrueCoders
  links:
  - https://twitter.com/truecodersio
  - https://www.facebook.com/truecodersio
  - https://www.linkedin.com/in/truecodersio
  - https://github.com/truecodersio
twitter:
  username: truecodersio
sass:
  style: compressed
baseurl: 
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
markdown: kramdown
permalink: pretty
plugins:
- jekyll-feed
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
