---
title: TrueCoders
timezone: America/Chicago
collections:
  courses:
    title: Courses
    output: true
  posts:
    title: Posts
    output: true
  team_members:
    title: Team Members
    output: true
    permalink: "/team/:path"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: courses
  values:
    layout: page
    image: 
    start_date: 
    end_date: 
    has_scholarship: true
    price: 
- scope:
    path: ''
    type: pages
  values:
    layout: plain-page
    is_nav_page: false
    hero_color: "#4b4948"
    hero_image: 
    display_title: 
    subtitle: 
    call_to_action:
      title: 
      url: 
- scope:
    path: admin.markdown
    type: pages
  values:
    display_title: TrueCoders CMS
    redirect_to: https://manage.siteleaf.com/sites/59928993035d0c67cfb24827
- scope:
    path: faqs.markdown
    type: pages
  values:
    layout: faqs
    qa_items:
    - question: 
      answer: 
- scope:
    path: index.markdown
    type: pages
  values:
    layout: home
    sections:
    - title: 
      body: 
      collection: 
      limit: 3
- scope:
    path: ''
    type: posts
  values:
    layout: page
    permalink: "/blog/:title/"
- scope:
    path: ''
    type: team
  values:
    layout: page
    company_title: 
    is_board_member: false
    is_teacher: false
    profile_image: 
url: http://truecoders.io
email: contact@truecoders.io
description: |-
  Be Mentored. Be Connected.

  We believe that smart, passionate people should always be engaged, doing what they love to do. Our mission is to educate smart and passionate people as they become skilled developers, to keep them engaged working with companies solving real-world problems, and to continue mentoring them as they grow their skill set.
company:
  name: TrueCoders
  full_name: TrueCoders LLC
  primary_color: "#0093C9"
author:
  picture: "/uploads/cody-winton.jpg"
  twitter: codytwinton
google_analytics:
  tracking_id: UA-104643272-1
logo: "/uploads/logo.png"
sass:
  style: compressed
social:
  name: TrueCoders
  links:
  - https://twitter.com/truecodersio
  - https://www.facebook.com/truecodersio
  - https://www.linkedin.com/in/truecodersio
  - https://github.com/truecodersio
twitter:
  username: truecodersio
baseurl: 
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
markdown: kramdown
permalink: pretty
plugins:
- jekyll-feed
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
