---
title: TrueCoders
timezone: America/Chicago
collections:
  coders:
    title: Coders
    output: true
  courses:
    title: Courses
    output: true
  faqs:
    title: FAQs
    output: false
  pagesections:
    title: PageSections
    output: false
    display_title: Page Sections
  posts:
    title: Posts
    output: true
  subjects:
    title: Subjects
    output: false
  teammates:
    title: Teammates
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: coders
  values:
    social:
      github: 
      linkedin: 
      codewars: 
    codewars:
    - 0
    skills:
    - title: 
      rank: 
    personality: 
    job_history_body: 
    reviews:
    - teammate: 
      review_body: 
- scope:
    path: ''
    type: courses
  values:
    layout: course
    hero_color: "#4b4948"
    hero_image: 
    subtitle: 
    image: 
    start_date: 
    weeks_length: 0
    has_scholarship: true
    price: 
    subjects:
    - 
    call_to_action:
      title: 
      url: 
- scope:
    path: ''
    type: pagesections
  values:
    display_title: 
    sub_collection: 
    limit: 3
    call_to_action:
      title: 
      url: 
    subsections:
    - title: 
      subtitle: 
      fa_icon: 
      body: 
- scope:
    path: ''
    type: posts
  values:
    layout: page
    permalink: "/blog/:title/"
- scope:
    path: ''
    type: teammates
  values:
    layout: page
    subtitle: 
    is_board_member: false
    is_teacher: false
    image: 
- scope:
    path: ''
    type: pages
  values:
    layout: page
    is_nav: false
    is_footer: false
    hero_color: "#4b4948"
    hero_image: 
    display_title: 
    subtitle: 
    call_to_action:
      title: 
      url: 
- scope:
    path: about.markdown
    type: pages
  values:
    layout: collection-page
    collection: teammates
- scope:
    path: courses.markdown
    type: pages
  values:
    layout: collection-page
    collection: courses
- scope:
    path: contact.markdown
    type: pages
  values:
    layout: contact
- scope:
    path: faqs.markdown
    type: pages
  values:
    layout: faqs
- scope:
    path: hire.markdown
    type: pages
  values:
    layout: hire
    pagesections:
    - 
- scope:
    path: index.markdown
    type: pages
  values:
    layout: index
    pagesections:
    - 
url: http://truecoders.io
logo: "/uploads/logo.png"
contact:
  email: contact@truecoders.io
  full_name: TrueCoders LLC
  phone: 12055308496
  address:
    street: 205 20th Street N
    unit: "#1015"
    city: Birmingham
    state: AL
    zip: '35203'
description: |-
  Be Mentored. Be Connected.

  We believe that smart, passionate people should always be engaged, doing what they love to do. Our mission is to educate smart and passionate people as they become skilled developers, to keep them engaged working with companies solving real-world problems, and to continue mentoring them as they grow their skill set.
google_analytics:
  tracking_id: UA-104643272-1
social:
  name: TrueCoders
  links:
  - https://twitter.com/truecodersio
  - https://www.facebook.com/truecodersio
  - https://www.linkedin.com/in/truecodersio
  - https://github.com/truecodersio
twitter:
  username: truecodersio
sass:
  style: compressed
baseurl: 
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
markdown: kramdown
permalink: pretty
plugins:
- jekyll-feed
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
