---
title: TrueCoders
timezone: America/Chicago
collections:
  courses:
    title: Courses
    output: true
  posts:
    title: Posts
    output: true
  team:
    title: Team Members
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: courses
  values:
    layout: page
    start_date: 
    end_date: 
    has_scholarship: true
    price: 
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: page
    permalink: "/blog/:title/"
- scope:
    path: ''
    type: team
  values:
    layout: page
    company_title: 
    is_board_member: false
    is_teacher: false
    profile_image: 
url: http://truecoders.io
email: contact@truecoders.io
description: Be Mentored. Be Connected.
company:
  name: TrueCoders LLC
  primary_color: "#0093C9"
author:
  picture: "/uploads/cody-winton.jpg"
  twitter: codytwinton
google_analytics:
  tracking_id: UA-104643272-1
logo: "/uploads/logo.png"
plugins:
- jekyll-feed
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
sass:
  sass_dir: styles/
  style: compressed
social:
  name: TrueCoders
  links:
  - https://twitter.com/truecodersio
  - https://www.facebook.com/truecodersio
  - https://www.linkedin.com/in/truecodersio
  - https://github.com/truecodersio
twitter:
  username: truecodersio
baseurl: 
destination: public
markdown: kramdown
permalink: pretty
source: src
